apiVersion: v1
kind: Service
metadata:
  labels:
    name: hasselblad500-app
  name: hasselblad500-app-svc
  namespace: hasselblad500
spec:
  type: LoadBalancer
  selector:
    app: hasselblad500-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
